# FROM alpine:latest

# USER root

# RUN echo "http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories
# RUN apk update
# RUN apk add docker
# RUN service docker start
FROM golang:1.9.0-alpine3.6

WORKDIR /go/src/github.com/msawangwan/ci.io

COPY . .

RUN go-wrapper download
RUN go-wrapper install

EXPOSE 80

CMD ["go-wrapper", "run"]
